### ISSUE TITLE
rpm.miracle.dk unavailable.

### ISSUE THREAD

**Issue by lingcherd** [MrMEEE/awx-build#309]
Looks like https://rpm.miracle.dk is unavailable. Pretty sure it was working a few days ago when I set up my UAT node. Will this be permanent?

Thanks.

**Comment by apoorvp2** [comment]
Hi ,

Same issue with  https://rpm.miracle.dk . Request your help here with the fix to the issue.

Thanks.

**Comment by dominiquearpin** [comment]
seem working now

**Comment by kapilkhub88** [comment]
Hi,

rpm.miracle.dk is down. Not able to proceed with deployment. Kindly help in fixing the issue.

**Comment by apoorvp2** [comment]
Hi,

The site https://rpm.miracle.dk/AWX-RPM/CentOS_7/ is not up . Kindly help with the fix as deployments are pending.

**Comment by yassertba** [comment]
Hello,

Any news on rpm.miracle.dk being down ?

Thanks

**Comment by thomasbrigsted** [comment]
Due to us working on the AWX-rpm turnkey application, this code was unfortunately messed up for a period of time. We are sorry for the incovenience. 
Everything should be working fine again now. If now, please let us know.

**Comment by tjyang** [comment]
@thomasbrigsted  Thanks for the update. 
Glad to know this project is still alive.  Looking forward to have another at https://awx.wiki/blog/almost-there

**Comment by arkram** [comment]
Hello, 
The problem still persist No directory for Centos7 on https://rpm.miracle.dk/AWX-RPM .
